Implicit|||||||||||Expansion|||||||||||0..52|0|Should students be taught to compete or to cooperate ?||||||||55..140|1|It is always said that competition can effectively promote the development of economy .|||||||||||||
EntRel||||||||||||||||||||||55..140|1|It is always said that competition can effectively promote the development of economy .||||||||142..283|2|In order to survive in the competition , companies continue to improve their products and service , and as a result , the whole society prospers .|||||||||||||
Implicit|||||||||||Expansion|||||||||||285..454|3|However , when we discuss the issue of competition or cooperation , what we are concerned about is not the whole society , but the development of an individual 's whole life .||||||||456..575|4|From this point of view , I firmly believe that we should attach more importance to cooperation during primary education .|||||||||||||
Implicit|||||||||||Expansion|||||||||||456..575|4|From this point of view , I firmly believe that we should attach more importance to cooperation during primary education .||||||||577..714|5|First of all , through cooperation , children can learn about interpersonal skills which are significant in the future life of all students .|||||||||||||
Implicit|||||||||||Expansion|||||||||||577..714|5|First of all , through cooperation , children can learn about interpersonal skills which are significant in the future life of all students .||||||||716..851|6|What we acquired from team work is not only how to achieve the same goal with others but more importantly , how to get along with others .|||||||||||||
Implicit|||||||||||Expansion|||||||||||716..851|6|What we acquired from team work is not only how to achieve the same goal with others but more importantly , how to get along with others .||||||||853..1086|7|During the process of cooperation , children can learn about how to listen to opinions of others , how to communicate with others , how to think comprehensively , and even how to compromise with other team members when conflicts occurred .|||||||||||||
Implicit|||||||||||Expansion|||||||||||853..1086|7|During the process of cooperation , children can learn about how to listen to opinions of others , how to communicate with others , how to think comprehensively , and even how to compromise with other team members when conflicts occurred .||||||||1088..1191|8|All of these skills help them to get on well with other people and will benefit them for the whole life .|||||||||||||
Implicit|||||||||||Expansion|||||||||||1378..1492|11|However , when we consider about the question that how to win the game , we always find that we need the cooperation .||||||||1494..1547|12|The greater our goal is , the more competition we need .|||||||||||||
EntRel||||||||||||||||||||||1549..1846|13|Take Olympic games which is a form of competition for instance , it is hard to imagine how an athlete could win the game without the training of his or her coach , and the help of other professional staffs such as the people who take care of his diet , and those who are in charge of the medical care .||||||||1848..1915|14|The winner is the athlete but the success belongs to the whole team .|||||||||||||
Implicit|||||||||||Expansion|||||||||||1848..1915|14|The winner is the athlete but the success belongs to the whole team .||||||||1917..1992|15|Therefore without the cooperation , there would be no victory of competition .|||||||||||||
